network:
  version: 2
  renderer: networkd
  ethernets:
    enp0s3: # Replace 'enp0s3' with your VM network interface name
      dhcp4: no
      addresses: [192.168.122.23/24] # Static IP address and subnet mask
      gateway4: 192.168.122.1 # Default gateway
      nameservers:
        addresses: # DNS servers
          - 8.8.8.8
          - 8.8.4.4 